backend:
  name: git-gateway
  branch: main
  repo: ivan-navarro-75/cassette
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "features"
    label: "Features"
    folder: "content/features/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Image"
        name: "thumbnail"
        widget: "image"
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "home.json"
        fields:
          - label: "Slug"
            name: "slug"
            widget: "string"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Overview"
            name: "overview"
            widget: "markdown"
          - label: "Featured Image"
            name: "thumbnail"
            widget: "image"
